#%RAML 1.0
title: ProstoTV
version: 1
baseUri: https://api.prosto.tv/v1
mediaType: application/json

securitySchemes:
  bearer:
    type: x-bearer
    describedBy:
      headers:
        Authorization:
          description: Заголовок для авторизации по токену
          example: Bearer 00112233445566778899aabbccddeeff

types:
  Bundle:
    type: object
    properties:
      id: integer
      main: [0, 1]
      bundles: array
      name_ru: string
      name_uk: string
  Device:
    type: object
    properties:
      id: string
      created: datetime
      updated: datetime
      password: string
      device: string
  Devices:
    type: object
    properties:
      id: string
      comment: string
  Error:
    type: object
    properties:
      code: integer
      message: string
  Operation:
    type: object
    properties:
      id: integer
      transaction_id: integer
      object_id: integer
      created: datetime
      sum: number
      balance: number
  Playlist:
    type: object
    properties:
      id: string
      created: datetime
      updated: datetime
      genres: [0, 1]
      comment: string
      ip: string
      url: string
  Playlists:
    type: object
    properties:
      id: string
      comment: string
      genres: [0, 1]
  Service:
    type: object
    properties:
      id: integer
      created: datetime
      name_ru: string
      name_uk: string
      cost: number
      start?: date-only
      stop?: date-only
  Token:
    type: object
    properties:
      token: string
  Status:
    type: object
    properties:
      id: string
      status:
        enum: [active, disconnected]

/bundles:
  /{id}:
    get:
      description: Получение списка каналов
      responses:
        200:
          body:
            type: object
            properties:
              id: integer
              name_uk: string
              name_ru: string
              channels: array
            example: |
              {
                "id": 108,
                "name_uk": "IPTV Всесвіт",
                "name_ru": "IPTV Вселенная",
                "channels": [
                  {
                    "number": 1,
                    "name_uk": "Україна",
                    "name_ru": "Украина"
                  },
                  {
                    "number": 2,
                    "name_uk": "Інтер",
                    "name_ru": "Интер"
                  },
                  {
                    "number": 6,
                    "name_uk": "Новий канал",
                    "name_ru": "Новый канал"
                  }
                ]
              }
        404:
          description: По заданому id услуги каналов не найдено
          body:
            type: Error

/objects:
  securedBy: bearer
  post:
    description: Добавление пользователя
    body:
      type: object
      properties:
        first_name?: string
        middle_name?: string
        last_name?: string
        note?: string
    responses:
      201:
        description: Пользователь добавлен
        body:
          type: object
          example: |
            {
              "id": 123456,
              "status": "active",
              "balance": 0,
              "bonus": 0,
              "bundles": [],
              "services": [],
              "devices": [],
              "playlists": []
            }
  /{id}:
    securedBy: bearer
    get:
      description: Получение данных пользователя
      responses:
        200:
          body:
            type: object
            properties:
              id: integer
              status: ['none', 'active', 'blocked', 'disconnected', 'deleted']
              balance: number
              bonus: number
              bundles: array
              services: array
              devices: array
              playlists: array
            example: |
              {
                "id": 123456,
                "status": "active",
                "balance": 0,
                "bonus": 0,
                "bundles": [
                  {
                    "id": 40,
                    "main": 1,
                    "bundles": [],
                    "name_ru": "Украина",
                    "name_uk": "Україна"
                  },
                  {
                    "id": 50,
                    "main": 1,
                    "bundles": [40],
                    "name_ru": "Вселенная",
                    "name_uk": "Всесвіт"
                  }
                ],
                "services": [
                  {
                    "id": 50,
                    "created": "2018-11-01 01:00:14",
                    "name_ru": "IPTV Вселенная",
                    "name_uk": "IPTV Всесвіт",
                    "cost": 79,
                    "stop": "2019-01-01"
                  }
                ],
                "devices": [
                  {
                    "id": "123456_3",
                    "created": "2018-11-01 02:01:04",
                    "updated": "2018-12-08 19:54:17",
                    "password": "520630",
                    "device": "M01PR100",
                    "comment": "Телевизор на кухне"
                  }
                ],
                "playlists": [
                  {
                    "id": "secret",
                    "created": "2018-12-01 12:14:34",
                    "updated": "2018-12-08 19:54:17",
                    "genres": 1,
                    "comment": "Домашний ПК",
                    "ip": "90.100.110.120",
                    "url": "http://my.prosto.tv/secret.m3u"
                  }
                ]
              }
    delete:
      description: Удаление учетки
      responses:
        200:
          description: Учетка удалена
          body:
            type: object
            example: |
              {
                "id": "123456",
                "status": "deleted"
              }
        305:
          description: Учетка удалена не полностью
          body:
            type: Error
        404:
          description: Учетка уже удалена
          body:
            type: Error
    /devices:
      securedBy: bearer
      post:
        description: Добавление устройства
        responses:
          201:
            description: Устройство добавлено
            body:
              type: Device
              example: |
                {
                  "id": "123456_3",
                  "created": "2018-11-01 02:01:04",
                  "updated": "2018-11-01 02:01:04",
                  "password": "520630",
                  "device": ""
                }
          406:
            description: Достугнут лимит
            body:
              type: Error
      /{device_id}:
        securedBy: bearer
        delete:
          description: Удаление устройства
          responses:
            200:
              description: Устройство удален
            400:
              description: Некорректный запрос
              body:
                type: Error
            404:
              description: Устройство не найдено
              body:
                type: Error
        put:
          description: Добавление комментария к устройству
          body:
            properties:
              comment: string
          responses:
            201:
              description: Комментарий добавлено
              body:
                type: Devices
                example: |
                  {
                    "id": "123456_3",
                    "comment": "Телевизор на кухне"
                  }
            400:
              description: Неверный id устройства
              body:
                type: Error
            204:
              description: Не задан комментарий
              body:
                type: Error

    /workoncredit:
      securedBy: bearer
      post:
        description: Активация работы в кредит
        responses:
          200:
            description: Работа в кредит активирована
          400:
            description: Не удалось активировать услугу
            body:
              type: Error
          402:
            description: Активация услуги недоступна
            body:
              type: Error
    /operations:
      securedBy: bearer
      post:
        description: Проведение операции
        body:
          type: object
          properties:
            operation_id: integer
            sum: number
          example: |
            {
              "operation_id": 20,
              "sum": 120.0
            }
        responses:
          201:
            description: Операция проведена
            body:
              type: Operation
              example: |
                {
                  "id": 123456,
                  "transaction_id": 123456,
                  "object_id": 123456,
                  "created": "2018-12-01 10:10:43",
                  "sum": 79.00,
                  "balance": 79.00
                }
          400:
            description: Некорректный запрос
            body:
              type: Error
          403:
            description: Указанный тип операции не разрешен
            body:
              type: Error
          404:
            description: Указанный тип операции не найден
            body:
              type: Error
          500:
            description: Внутренняя ошибка
            body:
              type: Error
    /playlists:
      securedBy: bearer
      post:
        description: Добавление плейлиста
        responses:
          201:
            description: Плейлист добавлен
            body:
              type: Playlist
              example: |
                {
                  "id": "secret",
                  "created": "2018-12-01 12:14:34",
                  "updated": "2018-12-01 12:14:34",
                  "genres": 1,
                  "comment": "",
                  "ip": "",
                  "url": "http://my.prosto.tv/secret.m3u"
                }
          406:
            description: Достугнут лимит
            body:
              type: Error
      /{playlist_id}:
        securedBy: bearer
        delete:
          description: Удаление плейлиста
          responses:
            200:
              description: Плейлист удален
            400:
              description: Некорректный запрос
              body:
                type: Error
            404:
              description: Плейлист не найден
              body:
                type: Error
        put:
          description: Добавление комментария, включение выключение группировки по жанрам
          body:
            properties:
              comment: string
              genres: integer
          responses:
            201:
              description: Плейлист изменен
              body:
                type: Playlists
                example: |
                  {
                    "id": secret,
                    "comment": "Домашний ПК",
                    "genres": 1
                  }
            400:
              description: Не указаны параметры
              body:
                type: Error
    /status:
      securedBy: bearer
      post:
        description: Отключение/включение учетной записи
        body:
          type: object
          properties:
            status: string
        responses:
          201:
            description: Статус учетной записи изменен
            body:
              type: Status
              example: |
                {
                  "id": 123456,
                  "status": "disconnected"
                }
          400:
            description: Некорректный запрос
            body:
              type: Error
          203:
            description: Неверный статус
            body:
              type: Error
          304:
            description: Статус уже установлен
            body:
              type: Error
          402:
            description: Недостаточно средств
            body:
              type: Error
          500:
            description: Внутренняя ошибка
            body:
              type: Error
    /services:
      securedBy: bearer
      post:
        description: Активация услуги
        body:
          type: object
          properties:
            id: integer
            auto_renewal: integer
        responses:
          201:
            description: Услуга активирована
            body:
              type: Service
              example: |
                {
                  "id": 50,
                  "created": "2018-11-01 01:00:14",
                  "name_ru": "IPTV Вселенная",
                  "name_uk": "IPTV Всесвіт",
                  "auto_renewal": 1,
                  "cost": 79
                }
          400:
            description: Некорректный запрос
            body:
              type: Error
          402:
            description: Недостаточно средств
            body:
              type: Error
          403:
            description: Нет прав для активации указанной услуги
            body:
              type: Error
          404:
            description: Услуга не найдена
            body:
              type: Error
          500:
            description: Внутренняя ошибка
            body:
              type: Error

/services:
  securedBy: bearer
  /{id}/accounts:
    get:
      description: Получить список аккаунтов, у которых включена указанная услуга
      responses:
        200:
          body:
            type: object
            properties:
              accounts: array
            example: |
              {
                "accounts": [ 1, 2, 3, ...],
              }

/token:
  post:
    description: Получение токена
    body:
      type: object
      properties:
        login: string
        password: string
    responses:
      201:
        description: Токен создан
        body:
          type: Token
          example: |
            {
              "token": "00112233445566778899aabbccddeeff"
            }
      400:
        description: Некорректный запрос, см. дополнительную информацию в ответе
        body:
          type: Error
      404:
        description: Указанная пара логин/пароль не найдена
        body:
          type: Error
